import { Contact } from "lucide-react";

export const locations = {
  "0": {
    name: "1 - Farmers With a Vision",
    lat: 0.302694,
    lng: 34.201,
    description: "Shop\nWorkshop",
    contact: "didacuspiusodhiambo@gmail.com\n+25472181018",
    products:
      "Box cookers\nConical cookers\nFuel Saving Stoves\nFireless cookers",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "1": {
    name: "8 - Asante Self Help Group",
    lat: 0.461678,
    lng: 34.110575,
    description: "ISC shop located in Mayenje\nNote: position is not exact",
    contact: "Odhiambo Innocent Franko",
    products: "",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "2": {
    name: "7 - Solarfire",
    lat: 0.115806,
    lng: 34.753083,
    description:
      "Solarfire has a demo site in Kisumu where they show the Lytefire 5.",
    contact: "Joan Arwa, joan.arwa@solarfire.io\n+254 723 444388",
    products: "",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "3": {
    name: "5 - Elisha Ochieng",
    lat: -0.07162,
    lng: 34.785127,
    description:
      "Position not exact.\nSelling solar cookers and fireless baskets",
    contact: "",
    products: "",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "4": {
    name: "6 - Thermofield Industrial",
    lat: -1.328542,
    lng: 36.697773,
    description:
      "Kenyan company specializing in clean energy through Concentrated Solar Heat (CSH), organic agricultural inputs (distilled wood vinegars, phosphorous recovery), and engineered environmental solutions for productive and manufacturing sectors in Africa.\nSpecializes in institutional solar kitchens with fixed-focus parabolic Scheffler dishes.",
    contact:
      "Charles Oloo, Technical Director\nThermofield Industrial\nNairobi, Kenya\nMobile: +254 (0)721 727 830/735 751 382\ninfo@thermofield.co.ke\nwww.thermofield.co.ke",
    products:
      "Institutional Solar Kitchens (Fixed-Focus Parabolic Scheffler Dishes)\nScheffler Reflectors\nConcentrated Solar Heat (CSH) Systems",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "5": {
    name: "2 - Asulma center workshop and shop",
    lat: -1.249896,
    lng: 36.883979,
    description: "\nUpdated: 2023-02-18",
    contact: "Samuel Odhiambo\nasulmacentre@gmail.com\n+254751530056\n\n",
    products:
      "Box cookers\nConical Cookers\nHaines Cookers\nFireless Cookers\nFuel Saving Stoves",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "6": {
    name: "9 - Shambani Millers Selfhelp Group",
    lat: -1.185704,
    lng: 37.446033,
    description: "",
    contact:
      "Sarah Ndunyo\nMobile: +254 114000564\nKithimani, close to Kithimani Primary School",
    products: "",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "7": {
    name: "3 - Tonembee",
    lat: -0.843004,
    lng: 37.731356,
    description:
      "Solar cooking shop\nMary Mumbi and Nicholas Kitembe\nKithuia Village\nKivaa Location",
    contact: "",
    products: "",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "8": {
    name: "4 - Athel Technology Limited",
    lat: -4.088521,
    lng: 39.625971,
    description: "Hybrid PV solar DC cookers",
    contact: "",
    products: "",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
  "9": {
    name: "10 - Green Leaf Champions CBO",
    lat: -1.331917,
    lng: 37.117278,
    description: "Promotion and awareness creation of Integrated Solar Cooking",
    contact:
      "Mary Iteba\nEmail: greenleafchampionscbo24@gmail.com\nMobile: +254 722 578396, +254 116 602874, +254 756 282249",
    products:
      "Solar Cookers (Haines 1.0, Conical, Box, Go Sun, Parabolic)\nFireless Cookers (Reed, Plastic)\nImproved Cooking Stoves (Multipurpose, Rocket, Kuni Mbili, KCJ)",
    color: "default",
    url: "default",
    type: "default",
    size: "default",
  },
};
