name: 🚀 Deploy website on push

on:
  push:
    branches:
      - test   # deploy to test subdomain on push to test branch

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Get latest code
        uses: actions/checkout@v4

      # If you have a build step (npm run build, etc.), add it here.
      - name: Build
        run: npm ci && npm run build

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/test.solarcookingkenya.co.ke/public_html/        # or ${{ secrets.FTP_TARGET_DIR }}
          local-dir: ./out/