name: 🚀 Deploy website on push to main

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Get latest code
        uses: actions/checkout@v4

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: npm
      # If you have a build step (npm run build, etc.), add it here.
      - name: Build
        run: npm ci && npm run build

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/solarcookingkenya.co.ke/public_html/
          local-dir: ./out/